from util import fib_generator, is_prime


def q001(a: int, b: int, limit: int) -> int:
    # If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.
    # Find the sum of all the multiples of 3 or 5 below 1000.

    if (a <= 0 or b <= 0 or limit <= 0):
        return 0
    return sum(i for i in range(limit) if i % a == 0 or i % b == 0)


def q002(limit: int) -> int:
    # Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
    # 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    # By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

    return sum(num for num in fib_generator(limit) if num % 2 == 0)


def q003(n: int) -> int:
    # The prime factors of 13195 are 5, 7, 13 and 29.
    # What is the largest prime factor of the number 600851475143 ?
    square_root = round(n ** 0.5)
    largest_candidate_below_sqrt_n = None
    for i in range(2, square_root + 1):
        if n % i == 0:
            factor_above_sqrt_n = n // i
            if is_prime(factor_above_sqrt_n):
                return factor_above_sqrt_n
            if is_prime(i):
                largest_candidate_below_sqrt_n = i
    return largest_candidate_below_sqrt_n
