import itertools
from polygonal_numbers import hexagonal_number, is_pentagonal, is_triangle


def p045(lower_limit: int = 40755):
    """ Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
        Triangle 	  	Tn=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
        Pentagonal 	  	Pn=n(3n−1)/2 	  	1, 5, 12, 22, 35, ...
        Hexagonal 	  	Hn=n(2n−1) 	  	1, 6, 15, 28, 45, ...
    It can be verified that T285 = P165 = H143 = 40755.
    Find the next triangle number that is also pentagonal and hexagonal.
    """
    hex_generator = (hexagonal_number(i) for i in itertools.count(1))
    return next(num for num in hex_generator
                if num > lower_limit
                and is_pentagonal(num)
                and is_triangle(num))
